
# #====[ CUSTOMIZATIONS ]====# #
SHOW-EXIT               = false
FPS                     = 120
TOP-OFFSET              = 50

# #====[ CONTROLS ]====# #
MOUSE-SENSITIVITY       = 1
SCROLL-SENSITIVITY      = 0.25
SCALE-TILE-UP           = ['up', '']    # 'up' will mean the arrow up
SCALE-TILE-DOWN         = ['down', '']  # 'down' means arrow down
TOGGLE-FULLSCREEN       = ['F11', '']
SAVE                    = ['s', 'ctrl']
LOAD                    = ['o', 'ctrl']
EXIT                    = ['escape', 'shift']
CANCEL-SELECTION        = ['escape', '']
SELECTION-ACCEPT        = ['return', ''] # 'return' is enter key
TILE-LOOKUP-REMOVAL     = ['delete', 'ctrl']
PROJECT-SELECTION-LEFT  = ['q', '']
PROJECT-SELECTION-RIGHT = ['e', '']
# tools
RECT                    = ['x', '']
BRUSH                   = ['w', '']


# #====[ FONTS ]====# #
HEADER-FONT             = 'Arial'
TEXT-FONT               = 'Arial'